# Generated by Django 3.1.7 on 2021-03-07 19:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0004_address_address_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
