# Generated by Django 3.1.7 on 2021-04-03 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0012_auto_20210403_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='charge',
            name='amount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='charge',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='charge',
            name='customer_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='charge',
            name='merchant_uid',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
