# Generated by Django 3.1.7 on 2021-04-03 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20210403_2234'),
        ('billing', '0013_auto_20210403_2355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charge',
            name='order_address',
        ),
        migrations.AddField(
            model_name='charge',
            name='imp_uid',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='charge',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.order'),
        ),
        migrations.AddField(
            model_name='charge',
            name='pg_tid',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='charge',
            name='receipt_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='charge',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='charge',
            name='timestamp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
