# Generated by Django 3.1.7 on 2021-04-03 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0015_auto_20210404_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charge',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
