# Generated by Django 3.1.7 on 2021-04-06 10:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('billing', '0015_auto_20210404_0033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingprofile',
            name='customer_id',
        ),
        migrations.RemoveField(
            model_name='card',
            name='billing_profile',
        ),
        migrations.RemoveField(
            model_name='card',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='card',
            name='country',
        ),
        migrations.RemoveField(
            model_name='card',
            name='default',
        ),
        migrations.RemoveField(
            model_name='card',
            name='exp_month',
        ),
        migrations.RemoveField(
            model_name='card',
            name='exp_year',
        ),
        migrations.RemoveField(
            model_name='card',
            name='last4',
        ),
        migrations.RemoveField(
            model_name='card',
            name='stripe_id',
        ),
        migrations.AddField(
            model_name='billingprofile',
            name='card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='billing.card'),
        ),
        migrations.AddField(
            model_name='card',
            name='card_name',
            field=models.CharField(default='abc', max_length=120),
        ),
        migrations.AddField(
            model_name='card',
            name='customer_uid',
            field=models.CharField(default='abc', max_length=120),
        ),
        migrations.AddField(
            model_name='card',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='card',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
