# Generated by Django 3.1.7 on 2021-04-06 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0016_auto_20210406_1912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charge',
            name='timestamp',
        ),
    ]
