# Generated by Django 3.1.7 on 2021-04-04 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0017_auto_20210404_1831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='active',
        ),
        migrations.RemoveField(
            model_name='card',
            name='billing_profile',
        ),
        migrations.RemoveField(
            model_name='card',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='card',
            name='country',
        ),
        migrations.RemoveField(
            model_name='card',
            name='default',
        ),
        migrations.RemoveField(
            model_name='card',
            name='exp_month',
        ),
        migrations.RemoveField(
            model_name='card',
            name='exp_year',
        ),
        migrations.RemoveField(
            model_name='card',
            name='last4',
        ),
        migrations.RemoveField(
            model_name='card',
            name='stripe_id',
        ),
        migrations.RemoveField(
            model_name='card',
            name='timestamp',
        ),
    ]
