# Generated by Django 3.1.7 on 2021-04-04 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0019_auto_20210404_2013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingprofile',
            name='customer_uid',
        ),
        migrations.AddField(
            model_name='billingprofile',
            name='card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='billing.card'),
        ),
    ]
