# Generated by Django 3.1.7 on 2021-04-06 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0020_auto_20210404_2017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='timestamp',
        ),
    ]
