# Generated by Django 3.1.7 on 2021-03-15 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='email',
        ),
        migrations.RemoveField(
            model_name='test',
            name='user',
        ),
    ]
