# Generated by Django 3.1.7 on 2021-03-15 18:46

from django.db import migrations, models
import staff.models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_auto_20210316_0242'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=staff.models.upload_main_image_path),
        ),
    ]
