# Generated by Django 2.0.13 on 2021-02-11 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_cart_subtotal'),
        ('carts', '0002_remove_cart_active'),
    ]

    operations = [
    ]
