# Generated by Django 3.1.7 on 2021-02-23 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_auto_20210224_0549'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='price',
            field=models.PositiveIntegerField(default=0, help_text='가격'),
        ),
    ]
