# Generated by Django 3.1.7 on 2021-02-24 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0005_auto_20210224_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='price',
            field=models.IntegerField(default=0, help_text='단가'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='subtotal',
            field=models.IntegerField(default=0, help_text='카트총액'),
        ),
    ]
