# Generated by Django 3.1.7 on 2021-03-02 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0038_auto_20210302_2109'),
        ('carts', '0007_auto_20210226_1455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='product_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.productitem'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='product_type',
            field=models.CharField(choices=[('normal', '상시상품구매'), ('bidding', '경매상품구매'), ('ticket', '경매티켓구매')], default='bidding', max_length=20),
        ),
    ]
