# Generated by Django 3.1.7 on 2021-03-02 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_ticketitem'),
        ('carts', '0008_auto_20210303_0349'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='ticker_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tickets.ticketitem'),
        ),
    ]
