# Generated by Django 3.1.7 on 2021-03-02 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0009_cartitem_ticker_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='ticker_item',
            new_name='ticket_item',
        ),
    ]
