# Generated by Django 3.1.7 on 2021-03-06 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0010_auto_20210303_0403'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='sale_ratio',
            field=models.DecimalField(decimal_places=1, default=0, help_text='할인율', max_digits=100),
        ),
    ]
