# Generated by Django 3.1.7 on 2021-03-13 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0012_auto_20210307_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='add_certificate',
            field=models.BooleanField(default=False),
        ),
    ]
