# Generated by Django 3.1.7 on 2021-03-13 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0013_cartitem_add_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='total',
            field=models.IntegerField(default=0, help_text='기타비용 포함 총액'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='subtotal',
            field=models.IntegerField(default=0, help_text='물품 총액'),
        ),
    ]
