# Generated by Django 3.1.7 on 2021-03-14 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0015_cartitem_is_reviewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('paid', 'Paid')], default='created', max_length=120),
        ),
    ]
