# Generated by Django 3.1.7 on 2021-03-24 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0016_cartitem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='option',
            field=models.CharField(default=0, help_text='옵션', max_length=20),
        ),
    ]
