# Generated by Django 3.1.7 on 2021-03-24 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0017_cartitem_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='option',
            field=models.CharField(blank=True, default=0, help_text='옵션', max_length=20, null=True),
        ),
    ]
