# Generated by Django 3.1.7 on 2021-04-30 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0018_auto_20210324_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='period',
            field=models.IntegerField(default=0),
        ),
    ]
