# Generated by Django 3.1.7 on 2021-05-02 13:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0019_cartitem_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='rental_start_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
