# Generated by Django 3.1.7 on 2021-05-02 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0022_auto_20210503_0156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='period',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
