# Generated by Django 3.1.7 on 2021-03-17 03:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(max_length=120, unique=True)),
                ('key', models.CharField(blank=True, max_length=120, null=True)),
                ('sent_mail', models.EmailField(max_length=254)),
                ('activated', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
