# Generated by Django 3.1.7 on 2021-03-21 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_registerticket'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registerticket',
            old_name='activated',
            new_name='shared',
        ),
    ]
