# Generated by Django 3.1.7 on 2021-03-21 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20210322_0103'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerticket',
            name='used',
            field=models.BooleanField(default=False),
        ),
    ]
