# Generated by Django 3.1.7 on 2021-03-24 11:03

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20210324_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(help_text='4~20글자 사이로 지정하십시오.', max_length=20, unique=True, validators=[django.contrib.auth.validators.ASCIIUsernameValidator]),
        ),
    ]
