# Generated by Django 3.1.7 on 2021-03-24 11:11

import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20210324_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(help_text='4~20글자 사이로 지정하십시오.', max_length=20, unique=True, validators=[django.core.validators.MinLengthValidator(4, '길이가 너무 짧습니다.'), django.contrib.auth.validators.ASCIIUsernameValidator]),
        ),
    ]
