# Generated by Django 3.1.7 on 2021-03-24 13:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20210324_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(help_text='4~20글자 사이로 지정하십시오.', max_length=20, unique=True, validators=[django.core.validators.MinLengthValidator(4, '길이가 너무 짧습니다.(4글자이상)'), django.core.validators.RegexValidator(message='아이디가 유효하지 않습니다.', regex='^(?=.{8,20}$)(?![_.])(?!.*[_.]{2})[a-zA-Z0-9._]+(?<![_.])$')]),
        ),
    ]
