# Generated by Django 3.1.7 on 2021-04-14 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20210325_0218'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerticket',
            name='sent_alimtalk',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='registerticket',
            name='sent_mail',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
