# Generated by Django 2.0.13 on 2021-01-18 13:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210118_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 18, 13, 39, 30, 618196, tzinfo=utc)),
        ),
    ]
