# Generated by Django 2.0.13 on 2021-01-19 18:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210118_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 19, 18, 1, 56, 47443, tzinfo=utc)),
        ),
    ]
