# Generated by Django 2.0.13 on 2021-01-22 07:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210120_0302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 22, 7, 42, 59, 93756, tzinfo=utc)),
        ),
    ]
