# Generated by Django 2.0.13 on 2021-01-22 16:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20210122_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 22, 16, 22, 29, 969664, tzinfo=utc)),
        ),
    ]
