# Generated by Django 2.0.13 on 2021-01-26 17:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20210123_0122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 26, 17, 32, 31, 210441, tzinfo=utc)),
        ),
    ]
