# Generated by Django 2.0.13 on 2021-01-29 17:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20210127_0243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 29, 17, 10, 21, 275293, tzinfo=utc)),
        ),
    ]
