# Generated by Django 2.0.13 on 2021-02-14 22:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20210215_0749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 14, 22, 54, 18, 485631, tzinfo=utc)),
        ),
    ]
