# Generated by Django 2.0.13 on 2021-02-15 05:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20210215_0754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 15, 5, 3, 17, 281554, tzinfo=utc)),
        ),
    ]
