# Generated by Django 2.0.13 on 2021-02-15 09:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20210215_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 15, 9, 25, 0, 261116, tzinfo=utc)),
        ),
    ]
