# Generated by Django 2.0.13 on 2021-02-17 06:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0047_auto_20210217_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 17, 6, 44, 0, 804960, tzinfo=utc)),
        ),
    ]
