# Generated by Django 2.0.13 on 2021-02-19 20:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0052_auto_20210218_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 19, 20, 52, 4, 744157, tzinfo=utc)),
        ),
    ]
