# Generated by Django 3.1.7 on 2021-02-21 09:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0057_auto_20210220_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 21, 9, 54, 52, 674988, tzinfo=utc)),
        ),
    ]
