# Generated by Django 3.1.7 on 2021-03-13 06:24

from django.db import migrations, models
import reviews.models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_auto_20210313_0721'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to=reviews.models.get_image_filename, verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='review',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to=reviews.models.get_image_filename, verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='review',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to=reviews.models.get_image_filename, verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='review',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to=reviews.models.get_image_filename, verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='review',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to=reviews.models.get_image_filename, verbose_name='Image'),
        ),
    ]
