# Generated by Django 3.1.7 on 2021-03-26 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_auto_20210314_1413'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='product_item',
            new_name='cart_item',
        ),
    ]
