# Generated by Django 2.0.13 on 2021-01-26 17:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0005_product_bidding_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyingTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0, help_text='수량')),
                ('buying_number', models.CharField(help_text='상품명', max_length=200)),
                ('user', models.ForeignKey(help_text='티켓구매자', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
