# Generated by Django 2.0.13 on 2021-01-29 17:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_buyingticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='shop/images'),
            preserve_default=False,
        ),
    ]
