# Generated by Django 2.0.13 on 2021-02-04 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
