# Generated by Django 3.1.7 on 2021-03-02 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TicketCart',
        ),
    ]
