# Generated by Django 2.0.13 on 2021-02-17 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_auto_20210218_0003'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TicketManager',
        ),
    ]
