# Generated by Django 3.1.7 on 2021-03-08 19:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_ticket_transfer_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='limit_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
