# Generated by Django 2.0.13 on 2021-02-17 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_delete_ticketmanager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='used',
        ),
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('unused', 'UNUSED'), ('activate', 'ACTIVATE'), ('used', 'USED')], default='unused', max_length=20),
        ),
    ]
