# Generated by Django 2.0.13 on 2021-02-18 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_auto_20210218_0254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='biddings',
        ),
    ]
