# Generated by Django 2.0.13 on 2021-02-17 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20210217_1730'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='ticket_cart',
            new_name='ticketcart',
        ),
    ]
