# Generated by Django 3.1.7 on 2021-03-04 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_delete_ticketorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='checkout_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='point_total',
            field=models.IntegerField(default=0),
        ),
    ]
