# Generated by Django 3.1.7 on 2021-03-07 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20210304_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_request',
            field=models.CharField(blank=True, help_text='고객요청사항', max_length=250, null=True),
        ),
    ]
