# Generated by Django 3.1.7 on 2021-04-11 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_order_cart_items_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancel_reson',
            field=models.CharField(blank=True, help_text='취소사유', max_length=250, null=True),
        ),
    ]
