# Generated by Django 3.1.7 on 2021-04-11 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_order_cancel_reson'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', '주문생성'), ('paid', '결제완료'), ('shipping', '배송중'), ('shipped', '배송완료'), ('refunded', '환불완료'), ('cancel', '결제취소')], default='created', max_length=120),
        ),
    ]
