# Generated by Django 2.0.13 on 2021-02-17 19:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('biddings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidding',
            name='bidding_price',
            field=models.PositiveIntegerField(default=0, help_text='경매참여가격'),
        ),
        migrations.AddField(
            model_name='bidding',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bidding',
            name='win',
            field=models.BooleanField(default=False),
        ),
    ]
