# Generated by Django 2.0.13 on 2021-02-18 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biddings', '0002_auto_20210218_0432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidding',
            name='bidding_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bidding',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Product'),
        ),
    ]
