# Generated by Django 2.0.13 on 2021-02-19 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biddings', '0003_auto_20210219_0459'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidding',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
