# Generated by Django 2.0.13 on 2021-02-06 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20210205_0517'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='info',
            new_name='description',
        ),
    ]
