# Generated by Django 2.0.13 on 2021-02-15 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20210206_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='list_price',
            field=models.PositiveIntegerField(default=0, help_text='정가'),
        ),
    ]
