# Generated by Django 2.0.13 on 2021-02-15 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_product_list_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='current_price',
            field=models.PositiveIntegerField(default=0, help_text='경매현재가격'),
        ),
    ]
