# Generated by Django 2.0.13 on 2021-02-15 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_product_current_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='info_delivery',
            field=models.CharField(default='택배', help_text='배송방법', max_length=30),
        ),
        migrations.AddField(
            model_name='product',
            name='info_delivery_from',
            field=models.CharField(default='국내', help_text='배송방법_국내해외', max_length=30),
        ),
        migrations.AddField(
            model_name='product',
            name='info_made_country',
            field=models.CharField(default=0, help_text='원산지', max_length=30),
        ),
        migrations.AddField(
            model_name='product',
            name='info_product_number',
            field=models.CharField(default=0, help_text='모델명', max_length=30),
        ),
        migrations.AddField(
            model_name='product',
            name='sale_ratio',
            field=models.DecimalField(decimal_places=1, default=0, help_text='할인율', max_digits=100),
        ),
    ]
