# Generated by Django 2.0.13 on 2021-02-15 22:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20210216_0714'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='bidding_date',
            new_name='bidding_start_date',
        ),
        migrations.AddField(
            model_name='product',
            name='bidding_end_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='경매종료일'),
        ),
        migrations.AddField(
            model_name='product',
            name='remain_bidding_time',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='남은경매시간'),
        ),
    ]
