# Generated by Django 2.0.13 on 2021-02-15 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20210216_0732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='remain_bidding_time',
            field=models.CharField(default=0, help_text='남은경매시간', max_length=200),
        ),
    ]
