# Generated by Django 2.0.13 on 2021-02-16 03:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20210216_0755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='bidding_start_date',
        ),
        migrations.AddField(
            model_name='product',
            name='bidding_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='경매시작일'),
        ),
    ]
