# Generated by Django 2.0.13 on 2021-02-16 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_auto_20210216_1228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='bidding_start_date',
            new_name='bidding_date',
        ),
    ]
