# Generated by Django 2.0.13 on 2021-02-16 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_auto_20210216_1810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='bidding',
        ),
    ]
