# Generated by Django 2.0.13 on 2021-02-19 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_remove_product_bidding'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_step',
            field=models.IntegerField(default=1000),
        ),
    ]
