# Generated by Django 2.0.13 on 2021-02-19 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_product_price_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='amount_always_on',
            field=models.IntegerField(default=0, help_text='상시판매수량'),
        ),
        migrations.AlterField(
            model_name='product',
            name='amount',
            field=models.IntegerField(default=0, help_text='경매수량'),
        ),
    ]
