# Generated by Django 3.1.7 on 2021-02-23 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_remove_product_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price_step',
            field=models.IntegerField(default=5000),
        ),
    ]
