# Generated by Django 3.1.7 on 2021-02-28 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_product_bidding_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='video_link',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='info_delivery_from',
            field=models.CharField(choices=[('domestic', '국내배송'), ('overseas', '해외배송')], default='국내', help_text='배송방법_국내해외', max_length=30),
        ),
    ]
