# Generated by Django 3.1.7 on 2021-02-28 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0030_auto_20210228_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='video_link',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
