# Generated by Django 3.1.7 on 2021-02-28 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0031_auto_20210228_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='remain_bidding_time',
            field=models.DurationField(default=0, help_text='남은경매시간'),
        ),
    ]
