# Generated by Django 3.1.7 on 2021-02-28 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0032_auto_20210228_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='remain_bidding_time',
            field=models.CharField(default=0, help_text='남은경매시간', max_length=200),
        ),
    ]
