# Generated by Django 3.1.7 on 2021-02-28 23:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0033_auto_20210228_2121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='product',
            name='amount_always_on',
        ),
        migrations.RemoveField(
            model_name='product',
            name='bidding_end_date',
        ),
        migrations.RemoveField(
            model_name='product',
            name='bidding_on',
        ),
        migrations.RemoveField(
            model_name='product',
            name='bidding_start_date',
        ),
        migrations.RemoveField(
            model_name='product',
            name='current_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='info_delivery_from',
        ),
        migrations.RemoveField(
            model_name='product',
            name='limit_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_step',
        ),
        migrations.RemoveField(
            model_name='product',
            name='remain_bidding_time',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sale_ratio',
        ),
        migrations.RemoveField(
            model_name='product',
            name='start_price',
        ),
        migrations.CreateModel(
            name='ProductItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info_delivery_from', models.CharField(choices=[('domestic', '국내배송'), ('overseas', '해외배송')], default='국내', help_text='배송방법_국내해외', max_length=30)),
                ('amount', models.IntegerField(default=0, help_text='판매수량(경매 or 일반')),
                ('sale_ratio', models.DecimalField(decimal_places=1, default=0, help_text='할인율', max_digits=100)),
                ('price', models.PositiveIntegerField(default=0, help_text='가격(일반가격 & 경매한도가)')),
                ('product_type', models.CharField(choices=[('normal', '상시상품구매'), ('bidding', '경매상품구매')], default='bidding', max_length=20)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('featured', models.BooleanField(default=True)),
                ('active', models.BooleanField(default=True)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, unique=True)),
                ('start_price', models.PositiveIntegerField(default=0, help_text='경매시작가격')),
                ('price_step', models.IntegerField(default=5000)),
                ('current_price', models.PositiveIntegerField(default=0, help_text='경매현재가격')),
                ('bidding_start_date', models.DateTimeField(default=django.utils.timezone.now, help_text='경매시작일')),
                ('bidding_end_date', models.DateTimeField(default=django.utils.timezone.now, help_text='경매종료일')),
                ('remain_bidding_time', models.CharField(default=0, help_text='남은경매시간', max_length=200)),
                ('bidding_on', models.CharField(choices=[('bidding_ready', '경매대기'), ('bidding', '경매중'), ('bidding_end', '경매종료')], default=0, help_text='경매여부', max_length=200)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
