# Generated by Django 3.1.7 on 2021-03-02 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0037_auto_20210301_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productitem',
            name='info_delivery_from',
            field=models.CharField(choices=[('domestic', '국내배송'), ('overseas', '해외배송')], default='domestic', help_text='배송방법_국내해외', max_length=30),
        ),
    ]
