# Generated by Django 3.1.7 on 2021-03-07 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0038_auto_20210302_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='info_alert',
            field=models.CharField(blank=True, help_text='취급시 주의사항_의류는 세탁방법 및 취급시 주의사항', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='info_as',
            field=models.CharField(blank=True, help_text='A/S 책임자와 전화번호', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='info_feature',
            field=models.CharField(blank=True, help_text='크기/치수/색상_구두/신발의경우_발길이 해외사이즈 표기시 국내사이즈 병행표기(mm), 굽높이:굽재료를 사용하는 여성화에 한함(cm)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='info_material',
            field=models.CharField(blank=True, help_text='제품소재_의류_섬유의 조성 또는 혼용률을 백분율로 표시, 기능성인 경우 성적서 또는 허가서, 운동화_경우에는 겉감, 안감을 구분하여 표시', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='info_product_kind',
            field=models.CharField(blank=True, help_text='종류_가방에 해당', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='info_product_person',
            field=models.CharField(blank=True, help_text='제조자_수입품인 경우 수입자를 함께 표기(변행수입의 경우 병행수입 여부로 대체 가능)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='info_quality_standard',
            field=models.CharField(blank=True, help_text='품질보증기준', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productitem',
            name='info_product_date',
            field=models.CharField(blank=True, help_text='제조연월_의류만 해당', max_length=100, null=True),
        ),
    ]
