# Generated by Django 3.1.7 on 2021-03-10 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0039_auto_20210307_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='productitem',
            name='option',
            field=models.BooleanField(default=False, help_text='옵션유무여부'),
        ),
        migrations.CreateModel(
            name='SizeOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField(default=0, help_text='사이즈')),
                ('amount', models.IntegerField(default=0, help_text='사이즈별수량')),
                ('product_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productitem')),
            ],
        ),
    ]
