# Generated by Django 3.1.7 on 2021-03-14 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0041_auto_20210312_0427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='number',
            field=models.CharField(blank=True, help_text='상품관리용코드', max_length=40, null=True, unique=True),
        ),
    ]
