# Generated by Django 3.1.7 on 2021-03-17 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0045_auto_20210317_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='productitem',
            name='description',
            field=models.TextField(blank=True, help_text='해당 물품아이템에만 있는 추가설명사항 기록(ex 경매면 보유사이즈 등)', null=True),
        ),
    ]
