# Generated by Django 3.1.7 on 2021-03-25 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0047_auto_20210318_0433'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='combined_delivery',
            field=models.BooleanField(default=True, help_text='합배송 여부_기본은 가능'),
        ),
    ]
