# Generated by Django 3.1.7 on 2021-04-29 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0048_product_combined_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productitem',
            name='product_type',
            field=models.CharField(choices=[('normal', '일반물품'), ('bidding', '경매물품'), ('rental', '렌탈물품')], default='normal', max_length=20),
        ),
    ]
