# Generated by Django 3.1.7 on 2021-05-09 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0050_auto_20210507_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productitem',
            name='featured',
            field=models.BooleanField(default=True),
        ),
    ]
